# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/linux/work/01.petalinux/bsp/zybo-z7-10-bsp/hardware/src/bd/system/ip/system_axi_gpio_eth_0/system_axi_gpio_eth_0.xci
# IP: The module: 'system_axi_gpio_eth_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/linux/work/01.petalinux/bsp/zybo-z7-10-bsp/hardware/src/bd/system/ip/system_axi_gpio_eth_0/system_axi_gpio_eth_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_eth_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/linux/work/01.petalinux/bsp/zybo-z7-10-bsp/hardware/src/bd/system/ip/system_axi_gpio_eth_0/system_axi_gpio_eth_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_eth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/linux/work/01.petalinux/bsp/zybo-z7-10-bsp/hardware/src/bd/system/ip/system_axi_gpio_eth_0/system_axi_gpio_eth_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_eth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/linux/work/01.petalinux/bsp/zybo-z7-10-bsp/hardware/src/bd/system/ip/system_axi_gpio_eth_0/system_axi_gpio_eth_0.xci
# IP: The module: 'system_axi_gpio_eth_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/linux/work/01.petalinux/bsp/zybo-z7-10-bsp/hardware/src/bd/system/ip/system_axi_gpio_eth_0/system_axi_gpio_eth_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_eth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/linux/work/01.petalinux/bsp/zybo-z7-10-bsp/hardware/src/bd/system/ip/system_axi_gpio_eth_0/system_axi_gpio_eth_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_eth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/linux/work/01.petalinux/bsp/zybo-z7-10-bsp/hardware/src/bd/system/ip/system_axi_gpio_eth_0/system_axi_gpio_eth_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_gpio_eth_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
